### ISSUE TITLE
Update supported eslint to include v9

### ISSUE THREAD

**Issue by jakebailey** [a-tarasyuk/eslint-formatter-autolinkable-stylish#33]
I'm working on upgrading TypeScript's eslint version to v9 now that ts-eslint supports it, but this package declares too low of a peer dep on eslint so npm doesn't want to install it without `--legacy-peer-deps`.

Can this package be updated to also say it supports v9? seems to work in my testing.

**Comment by a-tarasyuk** [comment]
@jakebailey Sure, I'll update it.
