### ISSUE TITLE
update eslint requirement to 7.5.x, still using 6.8.x

### ISSUE THREAD

**Issue by ravi005e** [a-tarasyuk/eslint-formatter-autolinkable-stylish#5]
update eslint requirement to 7.5.x, still using 6.8.x

eslint-formatter-autolinkable-stylish still using 6.8.x
Please update it

**Comment by a-tarasyuk** [comment]
Fixed https://github.com/a-tarasyuk/eslint-formatter-autolinkable-stylish/commit/9ceddc80afb45ac81f01a01a43e94c1f7a5b5e0d
